/**
 * Stable API error codes (PRD §6.5). Every error response is
 * { error: { code, message } }.
 */
export const ERROR_CODES = {
  DUPLICATE: "DUPLICATE",
  INVALID_INPUT: "INVALID_INPUT",
  RATE_LIMITED: "RATE_LIMITED",
  TURNSTILE_FAILED: "TURNSTILE_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  EVALUATION_UNAVAILABLE: "EVALUATION_UNAVAILABLE",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_STATUS: Record<ErrorCode, number> = {
  DUPLICATE: 409,
  INVALID_INPUT: 400,
  RATE_LIMITED: 429,
  TURNSTILE_FAILED: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  AI_UNAVAILABLE: 503,
  EVALUATION_UNAVAILABLE: 503,
  INTERNAL: 500,
};
