/**
 * WS8 seed data pools. Real college names (PRD Appendix A, verified Oct 2026),
 * fake student names. Everything else lives in scripts/seed.ts.
 */

export interface SeedCollege {
  id: string;
  name: string;
  shortName: string;
  city: string;
  state: string;
}

/** 40 real engineering colleges: 30 Telangana + 10 Andhra Pradesh. */
export const COLLEGES: readonly SeedCollege[] = [
  {
    id: "cbit",
    name: "Chaitanya Bharathi Institute of Technology",
    shortName: "CBIT",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "vnrvjiet",
    name: "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology",
    shortName: "VNR VJIET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "vasavi",
    name: "Vasavi College of Engineering",
    shortName: "Vasavi",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "griet",
    name: "Gokaraju Rangaraju Institute of Engineering and Technology",
    shortName: "GRIET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "mvsr",
    name: "MVSR Engineering College",
    shortName: "MVSR",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "cvr",
    name: "CVR College of Engineering",
    shortName: "CVR",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "kmit",
    name: "Keshav Memorial Institute of Technology",
    shortName: "KMIT",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "mgit",
    name: "Mahatma Gandhi Institute of Technology",
    shortName: "MGIT",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "snist",
    name: "Sreenidhi Institute of Science and Technology",
    shortName: "SNIST",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "vjit",
    name: "Vidya Jyothi Institute of Technology",
    shortName: "VJIT",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "anurag",
    name: "Anurag University",
    shortName: "Anurag",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "mrec",
    name: "Malla Reddy Engineering College",
    shortName: "MREC",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "jntuhceh",
    name: "JNTUH College of Engineering Hyderabad",
    shortName: "JNTUH CEH",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "bvritn",
    name: "B V Raju Institute of Technology",
    shortName: "BVRIT Narsapur",
    city: "Narsapur",
    state: "Telangana",
  },
  {
    id: "bvrit",
    name: "BVRIT Hyderabad College of Engineering for Women",
    shortName: "BVRIT Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "vardhaman",
    name: "Vardhaman College of Engineering",
    shortName: "Vardhaman",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "cmrcet",
    name: "CMR College of Engineering & Technology",
    shortName: "CMRCET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "gcet",
    name: "Geethanjali College of Engineering and Technology",
    shortName: "GCET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "matrusri",
    name: "Matrusri Engineering College",
    shortName: "Matrusri",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "mjcollege",
    name: "Muffakham Jah College of Engineering and Technology",
    shortName: "MJCET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "iare",
    name: "Institute of Aeronautical Engineering",
    shortName: "IARE",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "smec",
    name: "St. Martin's Engineering College",
    shortName: "SMEC",
    city: "Secunderabad",
    state: "Telangana",
  },
  {
    id: "methodist",
    name: "Methodist College of Engineering and Technology",
    shortName: "Methodist",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "stanley",
    name: "Stanley College of Engineering and Technology for Women",
    shortName: "Stanley",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "gnits",
    name: "G. Narayanamma Institute of Technology and Science",
    shortName: "GNITS",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "ngit",
    name: "Neil Gogte Institute of Technology",
    shortName: "NGIT",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "vbit",
    name: "Vignana Bharathi Institute of Technology",
    shortName: "VBIT",
    city: "Ghatkesar",
    state: "Telangana",
  },
  {
    id: "sicet",
    name: "Sri Indu College of Engineering and Technology",
    shortName: "SICET",
    city: "Ibrahimpatnam",
    state: "Telangana",
  },
  {
    id: "tkrcet",
    name: "TKR College of Engineering and Technology",
    shortName: "TKRCET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "biet",
    name: "Bharat Institute of Engineering and Technology",
    shortName: "BIET",
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "auce",
    name: "Andhra University College of Engineering",
    shortName: "AUCE",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
  },
  {
    id: "gvpce",
    name: "Gayatri Vidya Parishad College of Engineering",
    shortName: "GVPCE",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
  },
  {
    id: "viit",
    name: "Vignan's Institute of Information Technology",
    shortName: "VIIT",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
  },
  {
    id: "vrsec",
    name: "Velagapudi Ramakrishna Siddhartha Engineering College",
    shortName: "VRSEC",
    city: "Vijayawada",
    state: "Andhra Pradesh",
  },
  {
    id: "rvrjc",
    name: "RVR & JC College of Engineering",
    shortName: "RVRJC",
    city: "Guntur",
    state: "Andhra Pradesh",
  },
  {
    id: "srkr",
    name: "SRKR Engineering College",
    shortName: "SRKR",
    city: "Bhimavaram",
    state: "Andhra Pradesh",
  },
  {
    id: "vitb",
    name: "Vishnu Institute of Technology",
    shortName: "VIT Bhimavaram",
    city: "Bhimavaram",
    state: "Andhra Pradesh",
  },
  {
    id: "aditya",
    name: "Aditya Engineering College",
    shortName: "Aditya",
    city: "Surampalem",
    state: "Andhra Pradesh",
  },
  {
    id: "svec",
    name: "Sree Vidyanikethan Engineering College",
    shortName: "SVEC",
    city: "Tirupati",
    state: "Andhra Pradesh",
  },
  {
    id: "lbrce",
    name: "Lakireddy Bali Reddy College of Engineering",
    shortName: "LBRCE",
    city: "Mylavaram",
    state: "Andhra Pradesh",
  },
];

/** Fake first names for simulated students and ambassadors. */
export const FIRST_NAMES: readonly string[] = [
  "Aarav",
  "Aditya",
  "Aishwarya",
  "Akhil",
  "Ananya",
  "Anil",
  "Anjali",
  "Arjun",
  "Asha",
  "Bhavana",
  "Chaitanya",
  "Chandana",
  "Deepak",
  "Divya",
  "Ganesh",
  "Gayatri",
  "Harini",
  "Harsha",
  "Isha",
  "Jagadeesh",
  "Karthik",
  "Kavya",
  "Keerthi",
  "Kiran",
  "Lakshmi",
  "Madhav",
  "Manasa",
  "Manoj",
  "Meghana",
  "Nandini",
  "Nikhil",
  "Pavan",
  "Poornima",
  "Pranav",
  "Priya",
  "Rahul",
  "Rajesh",
  "Rakesh",
  "Ramya",
  "Ravi",
  "Rohan",
  "Sahithi",
  "Sai",
  "Sandeep",
  "Sanjay",
  "Sathvik",
  "Shruti",
  "Sindhu",
  "Sneha",
  "Srikanth",
  "Sruthi",
  "Suman",
  "Swathi",
  "Tejaswi",
  "Uday",
  "Vamsi",
  "Vandana",
  "Varun",
  "Venkatesh",
  "Viharika",
  "Vinay",
  "Yamini",
];

/** Fake last names for simulated students and ambassadors. */
export const LAST_NAMES: readonly string[] = [
  "Reddy",
  "Rao",
  "Kumar",
  "Sharma",
  "Naidu",
  "Chowdary",
  "Goud",
  "Yadav",
  "Verma",
  "Gupta",
  "Singh",
  "Patel",
  "Sastry",
  "Varma",
  "Raju",
  "Prasad",
  "Devi",
  "Kumari",
  "Teja",
  "Sai",
  "Krishna",
  "Murthy",
  "Babu",
  "Raj",
  "Shetty",
  "Nair",
  "Menon",
  "Pillai",
  "Das",
  "Bose",
  "Mishra",
  "Tiwari",
  "Pandey",
  "Joshi",
  "Desai",
  "Iyer",
  "Krishnan",
  "Venkatesan",
  "Subramanian",
];

/** Mobile browser user agents, including the WhatsApp in-app browser. */
export const USER_AGENTS: readonly string[] = [
  "Mozilla/5.0 (Linux; Android 14; Pixel 7a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Mobile Safari/537.36",
  "Mozilla/5.0 (Linux; Android 13; SM-M135F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Mobile Safari/537.36",
  "Mozilla/5.0 (Linux; Android 14; moto g84 5G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Mobile Safari/537.36",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1",
  "Mozilla/5.0 (Linux; Android 13; V2230) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Mobile Safari/537.36 WhatsApp/2.24.12.79",
  "Mozilla/5.0 (Linux; Android 14; Infinix X6837) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Mobile Safari/537.36",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 16_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.7 Mobile/15E148 Safari/604.1",
  "Mozilla/5.0 (Linux; Android 12; Redmi Note 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0 Mobile Safari/537.36",
];
